### ISSUE TITLE
poor synthesis

### ISSUE THREAD

**Issue by forwiat** [JackZiLong/LVCNet#6]
hello @zceng, thanks for your contribution in LVCNet.
I follow your default experiment's setting about training LJSpeech. Including sampling rate = 22050, batch_size = 8 and so on. But I have a poor synthesis although training reached checkpoint-180000.

real:
![image](https://user-images.githubusercontent.com/37399373/144557209-086d5059-498b-4163-8323-899f96764076.png)
generate:
![image](https://user-images.githubusercontent.com/37399373/144557240-17906b82-a58a-4871-bbe3-548eb6535cdd.png)
wavs zip:
[0100_wavs.zip](https://github.com/zceng/LVCNet/files/7647299/0100_wavs.zip)

Is it because not enough training? or other reasons?
Looking forward to your reply.
Thanks.

**Comment by forwiat** [comment]
Many important harmonic information is not clear from "generate" image.

**Comment by zceng** [comment]
180000 steps can get a passable results in my experiment. Can you  provide the figure of the loss curve ?

**Comment by forwiat** [comment]
![image](https://user-images.githubusercontent.com/37399373/144565179-c53d2108-762a-4b90-aca1-a68be2c3d6fd.png)
![image](https://user-images.githubusercontent.com/37399373/144565418-855dc5c4-3782-404f-b0da-03efa0de8b8f.png)
![image](https://user-images.githubusercontent.com/37399373/144565438-6d510c67-00eb-410c-97bd-edd7b2ad3846.png)

**Comment by forwiat** [comment]
Maybe it is converging?

**Comment by zceng** [comment]
you can compare the results of model at 100k step and 200k step, and whether the quality of generated speech were impoving.
